name: Portfolio CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Create new user
        shell: pwsh
        run: |
          $password = ConvertTo-SecureString -AsPlainText -Force 'QWE@#$asd234'
          New-LocalUser -Name "NUser" -Password $password -AccountNeverExpires:$true -Description "Remote Desktop User"

      - name: Add user to Remote Desktop Users group
        shell: pwsh
        run: Add-LocalGroupMember -Group "Remote Desktop Users" -Member "NUser"

      - name: Verify User Membership
        shell: pwsh
        run: Get-LocalGroupMember -Group "Remote Desktop Users"

      - name: Enable Remote Desktop for all users
        shell: pwsh
        run: |
          $rdp = Get-ItemProperty -Path 'HKLM:\SYSTEM\CurrentControlSet\Control\Terminal Server'
          $rdp.fDenyTSConnections = 0
          Set-ItemProperty -Path 'HKLM:\SYSTEM\CurrentControlSet\Control\Terminal Server' -Name fDenyTSConnections -Value 0

      - name: Enable Remote Desktop Firewall Rule
        shell: pwsh
        run: |
          $rule = Get-NetFirewallRule -DisplayName 'Remote Desktop - User Mode (TCP-In)'
          if ($rule -eq $null) {
            Write-Host "Remote Desktop Firewall Rule not found, creating it."
            New-NetFirewallRule -DisplayName 'Remote Desktop - User Mode (TCP-In)' -Direction Inbound -Protocol TCP -Action Allow -LocalPort 3389
          } else {
            Write-Host "Remote Desktop Firewall Rule already exists."
          }
